[supabase]
url = "https://uqblgzkffoyotqgsdski.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxYmxnemtmZm95b3RxZ3Nkc2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTIwNDcsImV4cCI6MjA3NDIyODA0N30.jZVyC-hAZLgxSCeoUxPlHNfFg8dZKEsYqJlpPn7NPKo"